# Generated by Django 4.0.4 on 2022-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_servicio_tiposervicio_remove_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='descripcionServicio',
            new_name='descripcionTipoServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcionServicio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Descripción'),
        ),
    ]
